<?php

$js_strings = array(
	__( 'Advertisement', 'advanced-gutenberg-blocks' ),
	__( 'Put forward a tips or a warning', 'advanced-gutenberg-blocks' ),
	__( 'ad', 'advanced-gutenberg-blocks' ),
	__( 'advertising', 'advanced-gutenberg-blocks' ),
	__( 'publicity', 'advanced-gutenberg-blocks' ),
	__( 'An ad will be displayed here in front', 'advanced-gutenberg-blocks' ),
	__( 'This button allow a customer to quickly add a product to cart', 'advanced-gutenberg-blocks' ),
	__( 'purchase', 'advanced-gutenberg-blocks' ),
	__( 'Add to cart', 'advanced-gutenberg-blocks' ),
	__( 'Add', 'advanced-gutenberg-blocks' ),
	__( 'to cart', 'advanced-gutenberg-blocks' ),
	__( 'Search Product', 'advanced-gutenberg-blocks' ),
	__( 'Background Color', 'advanced-gutenberg-blocks' ),
	__( 'Icon', 'advanced-gutenberg-blocks' ),
	__( 'Display Icon?', 'advanced-gutenberg-blocks' ),
	__( 'Text + Ad', 'advanced-gutenberg-blocks' ),
	__( 'Display a text on the left and a rectangle ad on the right', 'advanced-gutenberg-blocks' ),
	__( 'Write text here', 'advanced-gutenberg-blocks' ),
	__( 'Website card preview', 'advanced-gutenberg-blocks' ),
	__( 'Turn a simple url in a pretty card preview', 'advanced-gutenberg-blocks' ),
	__( 'url', 'advanced-gutenberg-blocks' ),
	__( 'link', 'advanced-gutenberg-blocks' ),
	__( 'Fetching website...', 'advanced-gutenberg-blocks' ),
	__( "⚠️ Error: Couldn't reach website", 'advanced-gutenberg-blocks' ),
	__( 'Type URL or paste', 'advanced-gutenberg-blocks' ),
	__( 'Apply', 'advanced-gutenberg-blocks' ),
	__( 'Loading...', 'advanced-gutenberg-blocks' ),
	__( 'No result', 'advanced-gutenberg-blocks' ),
	__( 'Geocode was not successful for the following reason:', 'advanced-gutenberg-blocks' ),
	__( 'Address', 'advanced-gutenberg-blocks' ),
	__( 'Type an address', 'advanced-gutenberg-blocks' ),
	__( 'Google Maps', 'advanced-gutenberg-blocks' ),
	__( 'Display a customizable Google map', 'advanced-gutenberg-blocks' ),
	__( 'gmap', 'advanced-gutenberg-blocks' ),
	__( 'Type your address on the inspector', 'advanced-gutenberg-blocks' ),
	__( '⚠️ You need to provide an API key in', 'advanced-gutenberg-blocks' ),
	__( 'Blocks > Installed Blocks > Google Map', 'advanced-gutenberg-blocks' ),
	__( 'Blocks > Installed Blocks > Card Preview', 'advanced-gutenberg-blocks' ),
	__( 'Marker Popup Title', 'advanced-gutenberg-blocks' ),
	__( 'My shop Name', 'advanced-gutenberg-blocks' ),
	__( 'Zoom', 'advanced-gutenberg-blocks' ),
	__( 'Height', 'advanced-gutenberg-blocks' ),
	__( 'Style', 'advanced-gutenberg-blocks' ),
	__( 'Advice', 'advanced-gutenberg-blocks' ),
	__( 'Avoid', 'advanced-gutenberg-blocks' ),
	__( 'Warning', 'advanced-gutenberg-blocks' ),
	__( 'Information', 'advanced-gutenberg-blocks' ),
	__( 'Notice', 'advanced-gutenberg-blocks' ),
	__( 'warning', 'advanced-gutenberg-blocks' ),
	__( 'information', 'advanced-gutenberg-blocks' ),
	__( 'tips', 'advanced-gutenberg-blocks' ),
	__( 'Your tip/warning content', 'advanced-gutenberg-blocks' ),
	__( 'Plugin', 'advanced-gutenberg-blocks' ),
	__( 'Display informations from a WordPress plugin', 'advanced-gutenberg-blocks' ),
	__( 'Search for a plugin in the inspector', 'advanced-gutenberg-blocks' ),
	__( 'Search plugin', 'advanced-gutenberg-blocks' ),
	__( '1+ Million', 'advanced-gutenberg-blocks' ),
	__( 'Less than 10', 'advanced-gutenberg-blocks' ),
	__( 'By', 'advanced-gutenberg-blocks' ),
	__( 'Active installations', 'advanced-gutenberg-blocks' ),
	__( 'Plugin page', 'advanced-gutenberg-blocks' ),
	__( "⚠️ Error: Couldn't reach wp.org", 'advanced-gutenberg-blocks' ),
	__( 'Search Plugin', 'advanced-gutenberg-blocks' ),
	__( 'Post', 'advanced-gutenberg-blocks' ),
	__( 'Display a pretty post link (from any post type)', 'advanced-gutenberg-blocks' ),
	__( 'Search for a post in the inspector', 'advanced-gutenberg-blocks' ),
	__( 'Choose a post', 'advanced-gutenberg-blocks' ),
	__( 'Customize', 'advanced-gutenberg-blocks' ),
	__( 'Show Image?', 'advanced-gutenberg-blocks' ),
	__( 'Show Author?', 'advanced-gutenberg-blocks' ),
	__( 'Show Category?', 'advanced-gutenberg-blocks' ),
	__( 'In', 'advanced-gutenberg-blocks' ),
	__( 'Read more', 'advanced-gutenberg-blocks' ),
	__( 'Loading post...', 'advanced-gutenberg-blocks' ),
	__( 'Product', 'advanced-gutenberg-blocks' ),
	__( 'Display WooCommerce Product in your post', 'advanced-gutenberg-blocks' ),
	__( 'woocommerce', 'advanced-gutenberg-blocks' ),
	__( 'Search for a product in the inspector', 'advanced-gutenberg-blocks' ),
	__( 'Choose a product', 'advanced-gutenberg-blocks' ),
	__( 'Price color', 'advanced-gutenberg-blocks' ),
	__( 'Button background color', 'advanced-gutenberg-blocks' ),
	__( 'Loading product...', 'advanced-gutenberg-blocks' ),
	__( 'Testimonial', 'advanced-gutenberg-blocks' ),
	__( 'Display a testimonial with a picture, text, name and company', 'advanced-gutenberg-blocks' ),
	__( 'review', 'advanced-gutenberg-blocks' ),
	__( '× Remove', 'advanced-gutenberg-blocks' ),
	__( 'Select Image', 'advanced-gutenberg-blocks' ),
	__( 'Write testimonial content here', 'advanced-gutenberg-blocks' ),
	__( 'Matt Mullenweg', 'advanced-gutenberg-blocks' ),
	__( 'Automattic', 'advanced-gutenberg-blocks' ),
	__( 'Show Company name?', 'advanced-gutenberg-blocks' ),
	__( 'Search a post', 'advanced-gutenberg-blocks' ),
	__( 'Type a post title', 'advanced-gutenberg-blocks' ),
	__( 'In post type', 'advanced-gutenberg-blocks' ),
	__( 'Type a product name', 'advanced-gutenberg-blocks' ),
);
